package main

import (
	"fmt"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/OWNER/jevkit/internal/sdlc/enrollment"
)

func (a *App) sdlcPolicyPath() string {
	return filepath.Join(a.WorkDir, ".jevkit", "sdlc", "policy.yaml")
}
func (a *App) sdlcRosterPath() string { return filepath.Join(a.ConfigDir, "sdlc", "roster.yaml") }

const sdlcEmptyRoster = "version: 1\nagents: []\n"

// Recognize only the exact starter previously generated by Jevkit. Edited
// rosters belong to the user and are never replaced.
const sdlcPreviousRosterStarter = `version: 1
# Only agents you add here can receive SDLC work.
# The default lean run needs planner, implementer, and assessor. One CLI agent
# can fill all three roles. Uncomment and edit the example below, or run:
# jevkit sdlc agents add codex --model MODEL --rubric "General work" --role all
agents:
  # - id: codex
  #   roles: [planner, implementer, assessor]
  #   rubric: Handle general repository work.
  #   via: runtime
  #   runtime: codex
  #   model: YOUR_MODEL
`

const sdlcThreeRoleRosterStarter = `version: 1
# The default lean run needs a planner, implementer, and assessor.
# Edit each entry's runtime and model, then set disabled: false to enroll it.
# Keep disabled: true for any role you do not want this agent to handle.
# A CLI app must be installed; check your setup with: jevkit sdlc doctor --policy lean
agents:
  - id: planner
    disabled: true
    roles: [planner]
    rubric: Plan the task and decide the next action.
    via: runtime
    runtime: codex
    model: YOUR_MODEL
  - id: implementer
    disabled: true
    roles: [implementer]
    rubric: Make the planned changes in the repository.
    via: runtime
    runtime: codex
    model: YOUR_MODEL
  - id: assessor
    disabled: true
    roles: [assessor]
    rubric: Review the result against the task and plan.
    via: runtime
    runtime: codex
    model: YOUR_MODEL
`

const sdlcRosterStarter = `version: 1
# These are editable examples, not enrolled agents. disabled: true keeps them off.
# Pick a supported model for each CLI, then set disabled: false to enroll it.
# IDs are your labels. roles decide which step an agent can do; rubric tells
# Jev when to choose it among eligible agents. Add more agents for any role.
# Check setup with: jevkit sdlc doctor --policy lean
agents:
  - id: claude-architect
    disabled: true
    roles: [planner]
    rubric: Plan complex changes and clarify the approach before implementation.
    via: runtime
    runtime: claude
    model: YOUR_MODEL
  - id: codex-builder
    disabled: true
    roles: [implementer]
    rubric: Implement planned code changes and report the result.
    via: runtime
    runtime: codex
    model: YOUR_MODEL
  - id: opencode-reviewer
    disabled: true
    roles: [assessor]
    rubric: Assess the code changes against the task and plan.
    via: runtime
    runtime: opencode
    model: YOUR_MODEL
  - id: codex-api-generalist
    disabled: true
    roles: [planner, implementer, assessor]
    rubric: API endpoint changes and regression fixes.
    roleRubrics:
      planner: Plan endpoint contracts and migrations.
      implementer: Update handlers and migration code.
      assessor: Check endpoint behavior and error handling.
    via: runtime
    runtime: codex
    model: YOUR_MODEL
`

// ensureSDLCRoster gives the path shown by `sdlc agents` a real file to open.
// An empty roster grants no agent permission, and O_EXCL preserves a roster
// another process may have created between the existence check and the write.
func (a *App) ensureSDLCRoster() error {
	if a.ConfigDir == "" {
		return fmt.Errorf("no user config directory for agent roster")
	}
	path := a.sdlcRosterPath()
	if raw, err := os.ReadFile(path); err == nil {
		if string(raw) == sdlcEmptyRoster || string(raw) == sdlcPreviousRosterStarter || string(raw) == sdlcThreeRoleRosterStarter {
			if err := writeAtomic(path, []byte(sdlcRosterStarter), 0o600); err != nil {
				return fmt.Errorf("write roster starter: %w", err)
			}
		}
		return nil
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("read roster %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create roster directory: %w", err)
	}
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o600)
	if os.IsExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("create roster: %w", err)
	}
	_, writeErr := f.WriteString(sdlcRosterStarter)
	closeErr := f.Close()
	if writeErr != nil {
		_ = os.Remove(path)
		return fmt.Errorf("write roster: %w", writeErr)
	}
	if closeErr != nil {
		_ = os.Remove(path)
		return fmt.Errorf("close roster: %w", closeErr)
	}
	return nil
}

// sdlcFileURL prints an absolute file URL so terminals can link paths that
// contain spaces or other URL-significant characters.
func sdlcFileURL(path string) string {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return path
	}
	urlPath := filepath.ToSlash(absolute)
	if filepath.VolumeName(absolute) != "" {
		urlPath = "/" + urlPath
	}
	return (&url.URL{Scheme: "file", Path: urlPath}).String()
}

func (a *App) sdlcEnrollment() (enrollment.Policy, enrollment.Roster, error) {
	p, err := enrollment.LoadPolicy(a.sdlcPolicyPath())
	if err != nil {
		return p, enrollment.Roster{}, err
	}
	r, err := enrollment.LoadRoster(a.sdlcRosterPath())
	return p, r, err
}

// CLI reach is derived from runnable binaries, not from agent definitions.
func (a *App) cliReach() enrollment.Reach {
	if a.SdlcReach != nil {
		return a.SdlcReach()
	}
	reach := enrollment.Reach{Driver: "cli", Runtimes: map[string]enrollment.RuntimeCapability{}, Binaries: map[string]enrollment.RuntimeCapability{}}
	lookPath := a.LookPath
	if lookPath == nil {
		lookPath = exec.LookPath
	}
	for runtime, binary := range map[string]string{"claude": "claude", "codex": "codex", "cursor": "cursor-agent", "opencode": "opencode", "antigravity": "agy"} {
		if _, err := lookPath(binary); err == nil {
			// Codex, Claude, and Cursor adapters use their read-only modes.
			// OpenCode has no enforced read-only CLI mode here.
			reach.Runtimes[runtime] = enrollment.RuntimeCapability{Write: true, ReadOnly: runtime != "opencode"}
		}
	}
	if roster, err := enrollment.LoadRoster(a.sdlcRosterPath()); err == nil {
		for _, ag := range roster.Agents {
			if ag.Via == enrollment.Runtime && ag.Binary != "" && (ag.Runtime == "claude" || ag.Runtime == "codex" || ag.Runtime == "cursor" || ag.Runtime == "opencode" || ag.Runtime == "antigravity") {
				if _, err := lookPath(ag.Binary); err == nil {
					reach.Binaries[ag.Binary] = enrollment.RuntimeCapability{Write: true, ReadOnly: ag.Runtime != "opencode"}
				}
			}
		}
	}
	return reach
}

func (a *App) sdlcAgentsDiscoverCmd() *cobra.Command {
	return &cobra.Command{Use: "discover", Short: "look at possible agents without adding them to your team", Args: cobra.NoArgs,
		Long: `Discover is a list of possibilities, not your team. It looks for
project and global runtime agent files, optional project suggestions in
.jevkit/sdlc/agents.yaml, and installed CLI apps. None can receive SDLC work
just because it appears here.

Use "sdlc agents add ID --role ROLE" to copy a named suggestion into your
personal roster. You can also create your own runtime agent directly with
"sdlc agents add". Use "sdlc agents" to see the roster Jevkit can use.
The copy is separate: editing the suggestion later does not update the roster.`,
		Example: "  jevkit sdlc agents discover\n  jevkit sdlc agents add security-reviewer --runtime codex --model MODEL --rubric 'Audit auth and secrets' --role security --read-only",
		RunE: func(*cobra.Command, []string) error {
			c, err := a.loadCatalog()
			if err != nil {
				return failf("%v", err)
			}
			for _, w := range c.Warnings {
				a.errf("jevkit: sdlc agents discover: warning: %s\n", w)
			}
			roster, err := enrollment.LoadRoster(a.sdlcRosterPath())
			if err != nil {
				return failf("%v", err)
			}
			enrolled := map[string]bool{}
			for _, agent := range roster.Agents {
				enrolled[agent.ID] = agent.Ready()
			}
			a.heading("DISCOVER = LOOK, NOT ADD")
			a.outf("  These are possible agents. Only agents in your roster can work.\n")
			a.outf("  Project suggestions in .jevkit/sdlc/agents.yaml appear here, not in your roster.\n")
			a.outf("\n")
			a.heading("NAMED SUGGESTIONS (project file and runtime agent files)")
			if len(c.IDs()) == 0 {
				a.outf("  none found\n")
			}
			for _, id := range c.IDs() {
				ag, _ := c.Agent(id)
				status := "not enrolled"
				if enrolled[id] {
					status = "enrolled"
				}
				binding := ag.Via
				switch ag.Via {
				case "runtime":
					binding = ag.Runtime + " / " + ag.Model
					if ag.RuntimeAgent != "" {
						binding += " / " + ag.RuntimeAgent
					}
				case "native":
					binding += " / " + ag.Subagent
				}
				a.outf("  %s  (%s; %s)\n    %s\n", id, binding, status, firstLine(ag.Rubric))
			}
			reach := a.cliReach()
			names := make([]string, 0, len(reach.Runtimes))
			for n := range reach.Runtimes {
				names = append(names, n)
			}
			sort.Strings(names)
			a.outf("\n")
			a.heading("CLI APPS ON PATH (apps, not agents or model lists)")
			if len(names) == 0 {
				a.outf("  none found\n")
			}
			for _, n := range names {
				binary := n
				switch n {
				case "cursor":
					binary = "cursor-agent"
				case "antigravity":
					binary = "agy"
				}
				a.outf("  %-10s binary: %s\n", n, binary)
			}
			a.outf("\n")
			a.heading("ADD = PUT AN AGENT ON YOUR TEAM")
			if len(c.IDs()) > 0 {
				a.outf("  Reuse a definition: jevkit sdlc agents add ID --role ROLE\n")
			}
			if len(names) > 0 {
				a.outf("  Add your own: jevkit sdlc agents add api-reviewer --runtime %s --model MODEL --rubric \"Review API contracts\" --role assessor\n", names[0])
			} else {
				a.outf("  Add your own: jevkit sdlc agents add api-reviewer --runtime codex --model MODEL --rubric \"Review API contracts\" --role assessor\n")
				a.outf("  Install that CLI before running; doctor checks reach.\n")
			}
			a.outf("  MODEL must be supported by the CLI. ROLE is planner, implementer, or assessor.\n")
			a.outf("  See your team: jevkit sdlc agents\n")
			a.outf("  Check setup: jevkit sdlc doctor --policy lean\n")
			return nil
		}}
}

func (a *App) sdlcAgentsAddCmd() *cobra.Command {
	var roles []string
	var roleRubricFlags []string
	var writeScopes []string
	var readOnly, isolated bool
	var via, subagent, runtime, model, runtimeAgent, rubric, binary string
	c := &cobra.Command{Use: "add <id>", Short: "put one agent in your personal SDLC roster", Args: cobra.ExactArgs(1),
		Long: `Add puts an agent on your SDLC team by writing to your personal
sdlc/roster.yaml. Jevkit creates the file if needed. You can also edit it
yourself.

You can copy a named suggestion shown by "sdlc agents discover": use its ID
and choose a role. Or create your own agent with --runtime, --model, --rubric,
and --role. For codex, claude, cursor, opencode, or antigravity, the CLI name can also be
the agent ID. Discovery is optional. Adding an agent does not install its
CLI; "sdlc doctor" checks whether it can actually run.`,
		Example: "  jevkit sdlc agents add security-reviewer --runtime codex --model MODEL --rubric 'Review authentication and secrets' --role security\n  jevkit sdlc agents add full-stack --runtime codex --model MODEL --rubric 'Web application work' --role all --role-rubric planner='Plan API changes' --role-rubric assessor='Review API behavior'",
		RunE: func(_ *cobra.Command, args []string) error {
			id := args[0]
			if a.ConfigDir == "" {
				return failf("no user config directory for agent roster")
			}
			if len(roles) == 0 {
				return usagef("--role is required: planner, implementer, assessor, research, qa, security, code-review, or all")
			}
			if len(roles) == 1 && roles[0] == "all" {
				roles = []string{"planner", "implementer", "assessor"}
			} else {
				for _, role := range roles {
					if role == "all" {
						return usagef("--role all must be used by itself")
					}
				}
			}
			ag := enrollment.Agent{ID: id, Roles: roles, Rubric: rubric, Via: via, Subagent: subagent, Runtime: runtime, Model: model, RuntimeAgent: runtimeAgent, Binary: binary}
			if len(roleRubricFlags) > 0 {
				ag.RoleRubrics = make(map[string]string, len(roleRubricFlags))
				for _, item := range roleRubricFlags {
					role, description, ok := strings.Cut(item, "=")
					if !ok || strings.TrimSpace(role) == "" || strings.TrimSpace(description) == "" {
						return usagef("--role-rubric requires ROLE=TEXT")
					}
					ag.RoleRubrics[role] = description
				}
			}
			if ag.Via == "" {
				if runtime != "" {
					ag.Via = enrollment.Runtime
				} else if subagent != "" {
					ag.Via = enrollment.Native
				} else if id == "host-self" {
					ag.Via = enrollment.HostSelf
					if ag.Rubric == "" {
						ag.Rubric = "The current host agent handles work directly."
					}
				} else if id == "codex" || id == "claude" || id == "cursor" || id == "opencode" || id == "antigravity" {
					ag.Via = enrollment.Runtime
					ag.Runtime = id
				} else {
					inv, err := a.loadCatalog()
					if err != nil {
						return failf("%v", err)
					}
					found, ok := inv.Agent(id)
					if !ok {
						return usagef("%q is not a named definition; to create your own agent, provide --runtime, --model and --rubric (discovery is optional)", id)
					} else {
						if found.RuntimeAgent != "" && found.Runtime != "claude" && found.Runtime != "opencode" && found.Runtime != "antigravity" {
							return usagef("%q is discoverable, but direct named-agent selection is not supported by the %s CLI adapter; use a runtime/model scaffold instead", id, found.Runtime)
						}
						ag.Via = found.Via
						ag.Subagent = found.Subagent
						ag.Runtime = found.Runtime
						if ag.Model == "" {
							ag.Model = found.Model
						}
						if ag.RuntimeAgent == "" {
							ag.RuntimeAgent = found.RuntimeAgent
						}
						ag.Binary = found.Binary
						ag.ReadOnly = found.ReadOnly
						ag.WriteScopes = found.WriteScopes
						if ag.Rubric == "" {
							ag.Rubric = found.Rubric
						}
					}
				}
			}
			if ag.Via == enrollment.Native && ag.Subagent == "" {
				ag.Subagent = id
			}
			if readOnly {
				ag.ReadOnly = true
			}
			if isolated {
				ag.Isolated = true
			}
			if len(writeScopes) > 0 {
				ag.WriteScopes = writeScopes
			}
			if ag.Via == enrollment.Runtime && ag.Model == "" {
				return usagef("--model is required for runtime %q; choose a model supported by that CLI", ag.Runtime)
			}
			if ag.Rubric == "" {
				return usagef("--rubric is required; describe when this agent should be chosen")
			}
			roster, err := enrollment.LoadRoster(a.sdlcRosterPath())
			if err != nil {
				return failf("%v", err)
			}
			for _, old := range roster.Agents {
				if old.ID == id {
					return failf("agent %q is already enrolled in %s", id, a.sdlcRosterPath())
				}
			}
			roster.Agents = append(roster.Agents, ag)
			if err := roster.Validate(); err != nil {
				return usagef("%v", err)
			}
			data, err := yaml.Marshal(roster)
			if err != nil {
				return failf("%v", err)
			}
			if err := os.MkdirAll(filepath.Dir(a.sdlcRosterPath()), 0o700); err != nil {
				return failf("%v", err)
			}
			if err := writeAtomic(a.sdlcRosterPath(), data, 0o600); err != nil {
				return failf("%v", err)
			}
			a.outf("added %s\nRoster: %s\nCheck eligibility: jevkit sdlc doctor --policy lean\n", id, sdlcFileURL(a.sdlcRosterPath()))
			return nil
		}}
	c.Flags().StringArrayVar(&roles, "role", nil, "planner, implementer, assessor, research, qa, security, code-review, or all (repeat for multiple roles)")
	c.Flags().StringVar(&via, "via", "", "binding: host-self, native or runtime")
	c.Flags().StringVar(&subagent, "subagent", "", "host native subagent name")
	c.Flags().StringVar(&runtime, "runtime", "", "CLI runtime name")
	c.Flags().StringVar(&model, "model", "", "runtime model binding")
	c.Flags().StringVar(&runtimeAgent, "agent", "", "named agent in the selected runtime")
	c.Flags().StringVar(&rubric, "rubric", "", "when Jev should choose this agent among eligible agents")
	c.Flags().StringArrayVar(&roleRubricFlags, "role-rubric", nil, "role-specific selection rubric, ROLE=TEXT (repeatable)")
	c.Flags().StringVar(&binary, "binary", "", "runtime binary override")
	c.Flags().BoolVar(&readOnly, "read-only", false, "enroll only when the driver can enforce read-only execution")
	c.Flags().BoolVar(&isolated, "isolated", false, "enroll only when the driver can enforce isolation")
	c.Flags().StringArrayVar(&writeScopes, "write-scope", nil, "allowed write scope (repeatable; requires driver enforcement)")
	return c
}

// Older scripts can keep using enroll, while help shows one verb for adding.
func (a *App) sdlcAgentsEnrollCmd() *cobra.Command {
	c := a.sdlcAgentsAddCmd()
	c.Use = "enroll <id>"
	c.Hidden = true
	return c
}

type preflight struct {
	Profile string
	Quorum  int
	Roles   map[string][]enrollment.Candidate
	Missing []string
}

func (a *App) sdlcPreflight(profile string, reach enrollment.Reach) (preflight, error) {
	p, r, err := a.sdlcEnrollment()
	if err != nil {
		return preflight{}, err
	}
	q, err := p.Quorum(profile)
	if err != nil {
		return preflight{}, err
	}
	result := preflight{Profile: profile, Quorum: q, Roles: map[string][]enrollment.Candidate{}}
	active := 0
	for _, ag := range r.Agents {
		if ag.Ready() {
			active++
		}
	}
	if len(r.Agents) == 0 {
		result.Missing = append(result.Missing, "no agents enrolled; default lean needs a planner, implementer, and assessor. One reachable CLI agent can cover all three: `jevkit sdlc agents add codex --model MODEL --rubric \"API endpoint changes\" --role all --role-rubric planner=\"Plan endpoint contracts\" --role-rubric assessor=\"Review API behavior\"`")
	} else if active == 0 {
		result.Missing = append(result.Missing, "no active agents; edit the roster shown by `jevkit sdlc agents`: set a real model and disabled: false for each needed role")
	}
	for _, role := range []string{"planner", "implementer", "assessor"} {
		write := role == "implementer"
		result.Roles[role] = enrollment.Eligible(p, r, reach, enrollment.Requirement{Role: role, Write: write})
		need := 1
		if role == "assessor" {
			need = q
		}
		if enrollment.DistinctBindings(result.Roles[role]) < need {
			result.Missing = append(result.Missing, fmt.Sprintf("%s: need %d eligible independent agent(s), have %d", role, need, enrollment.DistinctBindings(result.Roles[role])))
		}
	}
	return result, nil
}

func (a *App) sdlcDoctorCmd() *cobra.Command {
	var profile, driver string
	var native []string
	var hostSelf bool
	c := &cobra.Command{Use: "doctor", Short: "check enrollment, driver reach and policy quorum before a run", Args: cobra.NoArgs,
		RunE: func(*cobra.Command, []string) error {
			var reach enrollment.Reach
			switch driver {
			case "cli":
				reach = a.cliReach()
			case "host":
				reach = enrollment.Reach{Driver: "host", Self: hostSelf, Native: map[string]enrollment.HostCapability{}, Runtimes: a.cliReach().Runtimes}
				for _, n := range native {
					reach.Native[n] = enrollment.HostCapability{Write: true}
				}
			default:
				return usagef("--driver must be cli or host")
			}
			pf, err := a.sdlcPreflight(profile, reach)
			if err != nil {
				return failf("%v", err)
			}
			policy, _, err := a.sdlcEnrollment()
			if err != nil {
				return failf("%v", err)
			}
			a.outf("policy %s (assessment quorum %d, driver %s)\n", profile, pf.Quorum, driver)
			a.outf("  limits: %s\n", sdlcLimitSummary(policy))
			a.outf("  required: planner 1, implementer 1, assessor %d\n", pf.Quorum)
			for _, role := range []string{"planner", "implementer", "assessor"} {
				ids := []string{}
				for _, c := range pf.Roles[role] {
					ids = append(ids, c.Agent.ID)
				}
				need := 1
				if role == "assessor" {
					need = pf.Quorum
				}
				label := strings.Join(ids, ", ")
				if label == "" {
					label = "none"
				}
				a.outf("  %s: %d/%d eligible independent agents (%s)\n", role, enrollment.DistinctBindings(pf.Roles[role]), need, label)
			}
			if len(pf.Missing) > 0 {
				return failf("policy %s cannot start: %s", profile, strings.Join(pf.Missing, "; "))
			}
			a.outf("quorum possible\n")
			return nil
		}}
	c.Flags().StringVar(&profile, "policy", "lean", "policy profile: lean, collaborative or assured")
	c.Flags().StringVar(&driver, "driver", "cli", "driver mode: cli or host")
	c.Flags().StringArrayVar(&native, "host-native", nil, "native agent exposed by the host (diagnostic only)")
	c.Flags().BoolVar(&hostSelf, "host-self", false, "host exposes itself for work (diagnostic only)")
	return c
}
